[package]
name = "nhk4kindle"
version = "0.1.0"
authors = ["leandro"]
edition = "2018"

[dependencies]
select = "0.4.2"
reqwest = "0.9.9"
tempfile = "3.0.6"
regex = "1"
serde = "1.0"
serde_json = "1.0"
uuid = { version = "0.7", features = ["serde", "v4"] }
